name: safe_driving
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  permission_handler: ^11.3.1
  get: ^4.6.6
  shared_preferences: ^2.3.4
  just_audio: ^0.9.42
  kakao_flutter_sdk: ^1.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/sound/
    - assets/images/
    - assets/icons/
    - assets/icons/profile.png
    - assets/icons/bluetooth/
    - assets/icons/car/
    - assets/icons/check/
    - assets/icons/direction/
    - assets/icons/etc/
    - assets/icons/password/
    - assets/icons/phone/
    - assets/icons/play/
    - assets/icons/sound/
    - assets/icons/tabbar_fill/
    - assets/icons/tabbar_outline/

  fonts:
    - family: S-Core Dream
      fonts:
        - asset: assets/fonts/SCDream4.otf
          weight: 200
        - asset: assets/fonts/SCDream5.otf
          weight: 500
        - asset: assets/fonts/SCDream6.otf
          weight: 600
    - family: PyeongChang
      fonts:
        - asset: assets/fonts/PyeongChang-Regular.otf
          weight: 400