import 'package:flutter_svg/flutter_svg.dart';

class AppIcon{
  static const double width = 24;
  static const double height = 24;

  static SvgPicture bluetooth = SvgPicture.asset('assets/icons/bluetooth/bluetooth.svg', width: width, height: height,);
  static SvgPicture bluetoothDisable = SvgPicture.asset('assets/icons/bluetooth/bluetooth disable.svg', width: width, height: height,);
  static SvgPicture bluetoothSearching = SvgPicture.asset('assets/icons/bluetooth/bluetooth searching.svg', width: width, height: height,);
  static SvgPicture bluetoothNo = SvgPicture.asset('assets/icons/bluetooth/no.svg', width: width, height: height,);
  static SvgPicture blackCar = SvgPicture.asset('assets/icons/car/black car.svg', width: width, height: height,);
  static SvgPicture defaultCar = SvgPicture.asset('assets/icons/car/default car.svg', width: width, height: height,);
  static SvgPicture lightCar = SvgPicture.asset('assets/icons/car/light car.svg', width: width, height: height,);
  static SvgPicture check = SvgPicture.asset('assets/icons/check/check.svg', width: width, height: height,);
  static SvgPicture close = SvgPicture.asset('assets/icons/check/close.svg', width: width, height: height,);
  static SvgPicture downArrow = SvgPicture.asset('assets/icons/direction/down_arrow.svg', width: width, height: height,);
  static SvgPicture forwardArrow = SvgPicture.asset('assets/icons/direction/forward_arrow.svg', width: width, height: height,);
  static SvgPicture leftArrow = SvgPicture.asset('assets/icons/direction/left_arrow.svg', width: width, height: height,);
  static SvgPicture rightArrow = SvgPicture.asset('assets/icons/direction/right_arrow.svg', width: width, height: height,);
  static SvgPicture upArrow = SvgPicture.asset('assets/icons/direction/up_arrow.svg', width: width, height: height,);
  static SvgPicture backArrowIos = SvgPicture.asset('assets/icons/direction/back_arrow_ios.svg', width: width, height: height,);
  static SvgPicture forwardArrowIos = SvgPicture.asset('assets/icons/bluetooth/bluetooth.svg', width: width, height: height,);
  static SvgPicture bar = SvgPicture.asset('assets/icons/etc/bar.svg', width: width, height: height,);
  static SvgPicture email = SvgPicture.asset('assets/icons/etc/email.svg', width: width, height: height,);
  static SvgPicture locationMark = SvgPicture.asset('assets/icons/etc/location mark.svg', width: width, height: height,);
  static SvgPicture moon = SvgPicture.asset('assets/icons/etc/moon.svg', width: width, height: height,);
  static SvgPicture speed = SvgPicture.asset('assets/icons/etc/speed.svg', width: width, height: height,);
  static SvgPicture warning = SvgPicture.asset('assets/icons/etc/warning.svg', width: width, height: height,);
  static SvgPicture passwordOn = SvgPicture.asset('assets/icons/password/on.svg', width: width, height: height,);
  static SvgPicture passwordOff = SvgPicture.asset('assets/icons/password/off.svg', width: width, height: height,);
  static SvgPicture phoneDisable = SvgPicture.asset('assets/icons/phone/phone_disable.svg', width: width, height: height,);
  static SvgPicture phoneEnable = SvgPicture.asset('assets/icons/phone/phone_enable.svg', width: width, height: height,);
  static SvgPicture play = SvgPicture.asset('assets/icons/play/play.svg', width: width, height: height,);
  static SvgPicture playDisable = SvgPicture.asset('assets/icons/play/play_disable.svg', width: width, height: height,);
  static SvgPicture volumnOff = SvgPicture.asset('assets/icons/sound/volumn_off.svg', width: width, height: height,);
  static SvgPicture volumnUp = SvgPicture.asset('assets/icons/sound/volumn_up.svg', width: width, height: height,);
  static SvgPicture tabbarFillAlert = SvgPicture.asset('assets/icons/tabbar_fill/alert.svg', width: width, height: height,);
  static SvgPicture tabbarFillHome = SvgPicture.asset('assets/icons/tabbar_fill/home.svg', width: width, height: height,);
  static SvgPicture tabbarFillMusic = SvgPicture.asset('assets/icons/tabbar_fill/music.svg', width: width, height: height,);
  static SvgPicture tabbarFillProfile = SvgPicture.asset('assets/icons/tabbar_fill/profile.svg', width: width, height: height,);
  static SvgPicture tabbarOutlineAlert = SvgPicture.asset('assets/icons/tabbar_outline/alert.svg', width: width, height: height,);
  static SvgPicture tabbarOutlineHome = SvgPicture.asset('assets/icons/tabbar_outline/home.svg', width: width, height: height,);
  static SvgPicture tabbarOutlineMusic = SvgPicture.asset('assets/icons/tabbar_outline/music.svg', width: width, height: height,);
  static SvgPicture tabbarOutlineProfile = SvgPicture.asset('assets/icons/tabbar_outline/profile.svg', width: width, height: height,);
  static SvgPicture battery = SvgPicture.asset('assets/icons/battery.svg', width: width, height: height,);
  static SvgPicture group = SvgPicture.asset('assets/icons/group.svg', width: width, height: height,);
  static SvgPicture seat = SvgPicture.asset('assets/icons/seat.svg', width: width, height: height,);
  static SvgPicture logo = SvgPicture.asset('assets/images/logo.svg', width: 208, height: 67,);
  static SvgPicture googleLogin = SvgPicture.asset('assets/images/google login.svg', width: 343, height: 48,);
}